---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z0006149139TQM4S5M56A
          region: us-east-1
    email: brad@foghornconsulting.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
