apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
  namespace: istio-system
spec:
  selector:
    istio: internal-ingressgateway # use added internal controller
    #istio: ingressgateway # use istio default controller
  servers:
  #- port:
  #    number: 80
  #    name: http
  #    protocol: HTTP
  #  hosts:
  #  - "*"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*.istio.aws.bradandmarsha.com"
    tls:
      mode: SIMPLE # enables HTTPS on this port
      credentialName: internal-ingressgateway-certs
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo-blue
  namespace: istio-system
spec:
  hosts:
  - "nlborigin-blue.istio.aws.bradandmarsha.com"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        regex: /patient/.*/survey
    route:
    - destination:
        host: survey.bookinfo-blue.svc.cluster.local
        port:
          number: 5000
  - match:
    - uri:
        prefix: /patient
    route:
    - destination:
        host: patient.bookinfo-blue.svc.cluster.local
        port:
          number: 5000
  - match:
    - uri:
        prefix: /testprofile
    route:
    - destination:
        host: testprofile.bookinfo-blue.svc.cluster.local
        port:
          number: 5000
  - route:
    - destination:
        host: productpage.bookinfo-blue.svc.cluster.local
        port:
          number: 9080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo-green
  namespace: istio-system
spec:
  hosts:
  - "nlborigin-green.istio.aws.bradandmarsha.com"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        regex: /patient/.*/survey
    route:
    - destination:
        host: survey.bookinfo-green.svc.cluster.local
        port:
          number: 5000
  - match:
    - uri:
        prefix: /patient
    route:
    - destination:
        host: patient.bookinfo-green.svc.cluster.local
        port:
          number: 5000
  - match:
    - uri:
        prefix: /testprofile
    route:
    - destination:
        host: testprofile.bookinfo-green.svc.cluster.local
        port:
          number: 5000
  - route:
    - destination:
        host: productpage.bookinfo-green.svc.cluster.local
        port:
          number: 9080
---
