apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
  namespace: istio-system
spec:
  selector:
    istio: internal-ingressgateway # use added internal controller
    #istio: ingressgateway # use istio default controller
  servers:
  #- port:
  #    number: 80
  #    name: http
  #    protocol: HTTP
  #  hosts:
  #  - "*"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE # enables HTTPS on this port
      credentialName: internal-ingressgateway-certs
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        regex: /patient/.*/survey
    route:
    - destination:
        host: survey.bookinfo.svc.cluster.local
        port:
          number: 5000
  - match:
    - uri:
        prefix: /patient
    route:
    - destination:
        host: patient.bookinfo.svc.cluster.local
        port:
          number: 5000
  - match:
    - uri:
        prefix: /testprofile
    route:
    - destination:
        host: testprofile.bookinfo.svc.cluster.local
        subset: v1
        port:
          number: 5000
      weight: 50
    - destination:
        host: testprofile.bookinfo.svc.cluster.local
        subset: v2
        port:
          number: 5000
      weight: 50
  - route:
    - destination:
        host: productpage.bookinfo.svc.cluster.local
        port:
          number: 9080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: testprofile
  namespace: istio-system
spec:
  host: testprofile.bookinfo.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
